#!/bin/bash

# Selected text translator by ibrahim mohammad
# Email: ibrahim.mohammad.2015@gmail.com
# GitHub repository: https://github.com/IbrahimMohammad/st-trans
# No Rights Reserved

# Debian based systems installer script

# if non root user run the script
if [ $EUID -ne 0 ]; then
    echo 'This script must be run as root. use command sudo ./st-trans or su -c ./st-trans to run it.'
    exit 1
fi
# install depends
apt-get --assume-yes install libnotify-bin xsel xbindkeys || exit 1
# download st-trans
wget -qO /usr/bin/st-trans \
"https://raw.githubusercontent.com/IbrahimMohammad/st-trans/master/bin/st-trans" || exit 1
chmod 755 /usr/bin/st-trans
# download daemon
wget -qO /usr/bin/st-trans-daemon \
"https://raw.githubusercontent.com/IbrahimMohammad/st-trans/master/bin/st-trans-daemon" || exit 1
chmod 755 /usr/bin/st-trans-daemon
# autostart auto adjust translation view
wget -qO /etc/xdg/autostart/st-trans-view.desktop \
"https://raw.githubusercontent.com/IbrahimMohammad/st-trans/master/autostart/st-trans-view.desktop" || exit 1
echo 'st-trans has been installed successfully. run command st-trans just for the first time after the installation. then you can use the shortcut key Alt + t to translate any selected text at any time :)'
exit
