#!/bin/bash

# Selected text translator installer script by ibrahim mohammad
# Email: ibrahim.mohammad.2015@gmail.com
# GitHub repository: https://github.com/IbrahimMohammad/shell_script
# No Rights Reserved

# if non root user run the script
if [ $EUID -ne 0 ]; then
    echo 'This script must be run as root. use command sudo ./st-trans or su -c ./st-trans to run it.'
    echo 'يجب تشغيل هذا السكربت كمستخدم جذر. استخدم الأمر sudo ./st-trans أو su -c ./st-trans لتشغيله.'
    exit 1
fi
# install depends for fedora or debian
if cat /usr/lib/os-release | grep -qF 'Fedora'; then
    dnf --assumeyes install libnotify xsel xbindkeys || exit 1
else
    apt-get --assume-yes install libnotify-bin xsel xbindkeys || exit 1
fi
# download st-trans
wget -qO /usr/bin/st-trans \
"https://raw.githubusercontent.com/IbrahimMohammad/shell_script/master/st-trans/bin/st-trans" || exit 1
chmod 755 /usr/bin/st-trans
# get the logged in user
if [ -n "$SUDO_USER" ]; then
    user=$SUDO_USER
else
    user=$USERNAME
fi
# download .st-trans
su --command - $user 'wget -qO ~/.st-trans \
"https://raw.githubusercontent.com/IbrahimMohammad/shell_script/master/st-trans/.st-trans" || exit 1'
su --command - $user 'chmod 755 .st-trans'
# add script to shortcut key
su --command - $user 'echo "\"~/.st-trans\"" >> ~/.xbindkeysrc'
su --command - $user 'echo "Alt + t" >> ~/.xbindkeysrc'
# update xbindkeys to use the new shortcut key
su --command - $user 'xbindkeys'
# send notify to the user
su --command - $user 'notify-send -t 0 -u critical "تم تثبيت st-trans بنجاح :)" "حدد النص ثم اضغط Alt + t وستظهر الترجمة هنا."'
exit
