#!/bin/bash

# Selected text translator by ibrahim mohammad
# Email: ibrahim.mohammad.2015@gmail.com
# GitHub repository: https://github.com/IbrahimMohammad/shell_script
# No Rights Reserved

# Fedora installer script

# if non root user run the script
if [ $EUID -ne 0 ]; then
    echo 'This script must be run as root. use command sudo -E ./st-trans to run it.'
    echo 'يجب تشغيل هذا السكربت كمستخدم جذر. استخدم الأمر sudo -E ./st-trans لتشغيله.'
    exit 1
fi
# install depends
dnf --assumeyes install xsel xbindkeys || exit 1
# make xbindkeys autostart
wget -qO /etc/xdg/autostart/xbindkeys.desktop \
"https://raw.githubusercontent.com/IbrahimMohammad/st-trans/master/autostart/xbindkeys.desktop" || exit 1
# download st-trans
wget -qO /usr/bin/st-trans \
"https://raw.githubusercontent.com/IbrahimMohammad/st-trans/master/bin/st-trans" || exit 1
chmod 755 /usr/bin/st-trans
# download daemon
wget -qO /usr/bin/st-trans-daemon \
"https://raw.githubusercontent.com/IbrahimMohammad/st-trans/master/bin/st-trans-daemon" || exit 1
chmod 755 /usr/bin/st-trans-daemon
# get logged in username
if [ -n "$SUDO_USER" ]; then
    user=$SUDO_USER
else
    user=$USERNAME
fi
# download .st-trans
su --command - $user 'wget -qO ~/.st-trans \
"https://raw.githubusercontent.com/IbrahimMohammad/st-trans/master/.st-trans" || exit 1'
su --command - $user 'chmod 755 .st-trans'
# add script to shortcut key
su --command - $user 'echo "\"~/.st-trans\"" >> ~/.xbindkeysrc'
su --command - $user 'echo "Alt + t" >> ~/.xbindkeysrc'
# update xbindkeys to use the new shortcut key
su --command - $user 'xbindkeys'
# send notify to the user
su --command - $user 'notify-send -t 0 -u critical "تم تثبيت st-trans بنجاح :)" "حدد النص ثم اضغط Alt + t وستظهر الترجمة هنا."'
exit
